httpd:
  build: $PWD
  links:
   - maria_db:db
  ports:
   - 80:80
  volumes:
   - $PWD:/var/www/html
  environment:
    DB_ENV_MYSQL_USER: root
    DB_ENV_MYSQL_PASSWORD: docker
    BUILD_STAGE: docker-compose
maria_db:
  container_name: mariadb
  image: mariadb
  volumes:
   - $PWD/sql/staging.sql:/docker-entrypoint-initdb.d/staging.sql
  environment:
    MYSQL_ROOT_PASSWORD: toto
    MYSQL_DATABASE: sqli
  expose:
   - "3306"
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
   - maria_db:db
  ports:
   - 8181:80
  environment:
    PMA_USER: root
PMA_PASSWORD: toto
