httpd:
  build: $PWD
  links:
   - mysql:db
  ports:
   - 80:80
  volumes:
   - $PWD:/var/www/html
  environment:
    DB_ENV_MYSQL_USER: root
    DB_ENV_MYSQL_PASSWORD: docker
    BUILD_STAGE: docker-compose
mysql:
  container_name: mysql
  image: mysql
  volumes:
   - $PWD/sql/arjs.sql:/docker-entrypoint-initdb.d/arjs.sql
  environment:
    MYSQL_ROOT_PASSWORD: lpdw2017
    MYSQL_DATABASE: arjs_kwry
  expose:
   - "3306"
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
   - mysql:db
  ports:
   - 8181:80
  environment:
    PMA_USER: arjs_kwry
    PMA_PASSWORD: lpdw2017
